#!/usr/bin/env bash
# setup.sh — AAAgents OSS First-Time Setup
#
# Generates cryptographically secure secrets and creates .env.oss from the
# bundled template. Run this ONCE before your first `docker compose up`.
#
# Compatible with: macOS, Linux, Git Bash (Windows)
# Requires:        Python 3 (already required by the stack)
#
# Usage:
#   bash setup.sh

set -euo pipefail

ENV_FILE=".env.oss"
ENV_EXAMPLE=".env.oss.example"

# ── Terminal colours (graceful degradation if not supported) ──────────────────
if [ -t 1 ] && command -v tput &>/dev/null && tput colors &>/dev/null 2>&1; then
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    CYAN='\033[0;36m'
    RED='\033[0;31m'
    BOLD='\033[1m'
    NC='\033[0m'
else
    GREEN=''; YELLOW=''; CYAN=''; RED=''; BOLD=''; NC=''
fi

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║        AAAgents OSS — First-Time Setup                   ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

# ── Guard: don't overwrite existing config ────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}⚠  .env.oss already exists — skipping.${NC}"
    echo ""
    echo "   Your existing configuration is unchanged."
    echo "   To regenerate from scratch: rm .env.oss && bash setup.sh"
    echo ""
    exit 0
fi

# ── Pre-flight checks ─────────────────────────────────────────────────────────
if [ ! -f "$ENV_EXAMPLE" ]; then
    echo -e "${RED}❌ .env.oss.example not found.${NC}"
    echo "   Make sure you are in the aaagents-oss root directory."
    exit 1
fi

# Resolve Python (python3 preferred; fall back to python on Windows/Git Bash)
if command -v python3 &>/dev/null; then
    PYTHON="python3"
elif command -v python &>/dev/null; then
    # Verify it is Python 3 — the secrets module does not exist in Python 2
    if python -c "import sys; sys.exit(0 if sys.version_info >= (3, 6) else 1)" 2>/dev/null; then
        PYTHON="python"
    else
        echo -e "${RED}❌ 'python' found but is not Python 3.6+.${NC}"
        echo "   Install Python 3 from https://www.python.org/downloads/ and retry."
        exit 1
    fi
else
    echo -e "${RED}❌ Python 3 not found.${NC}"
    echo "   Install Python 3 from https://www.python.org/downloads/ and retry."
    exit 1
fi

# ── Generate secrets ──────────────────────────────────────────────────────────
echo "Generating cryptographically secure secrets..."

POSTGRES_PASSWORD=$("$PYTHON" -c "import secrets; print(secrets.token_hex(24))")
PROXY_SECRET=$("$PYTHON" -c "import secrets; print(secrets.token_hex(32))")

# Sanity check — should never fail, but fail loudly if it does
if [ -z "$POSTGRES_PASSWORD" ] || [ -z "$PROXY_SECRET" ]; then
    echo -e "${RED}❌ Secret generation failed — Python output was empty.${NC}"
    exit 1
fi

# ── Write .env.oss ────────────────────────────────────────────────────────────
# Use awk for portable replacement of the empty POSTGRES_PASSWORD= line.
awk -v pw="$POSTGRES_PASSWORD" '
    /^POSTGRES_PASSWORD=[[:space:]]*$/ { print "POSTGRES_PASSWORD=" pw; next }
    { print }
' "$ENV_EXAMPLE" > "$ENV_FILE"

# Append PROXY_ENGINE_SHARED_SECRET section.
# Use printf instead of heredoc to avoid shell interpolation of $PROXY_SECRET.
# A heredoc with double-quotes would interpolate special chars (e.g. if token
# format ever changes from hex to url-safe base64 which contains +/=).
printf '\n' >> "$ENV_FILE"
printf '# \u2500\u2500\u2500 Internal Service Authentication \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n' >> "$ENV_FILE"
printf '# Auto-generated by setup.sh \u2014 do NOT commit this file or share this value.\n' >> "$ENV_FILE"
printf '# HMAC-SHA256 key signing requests from the Public API to the Backend Engine.\n' >> "$ENV_FILE"
printf 'PROXY_ENGINE_SHARED_SECRET=%s\n' "$PROXY_SECRET" >> "$ENV_FILE"

# ── Create required directories ───────────────────────────────────────────────
mkdir -p data plugins

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}✅ .env.oss created successfully.${NC}"
echo ""
echo -e "${BOLD}┌──────────────────────────────────────────────────────────┐${NC}"
echo -e "${BOLD}│  Auto-generated secrets (stored only in .env.oss):       │${NC}"
echo -e "${BOLD}│                                                          │${NC}"
echo -e "${BOLD}│  POSTGRES_PASSWORD            ✓  generated               │${NC}"
echo -e "${BOLD}│  PROXY_ENGINE_SHARED_SECRET   ✓  generated               │${NC}"
echo -e "${BOLD}│                                                          │${NC}"
echo -e "${BOLD}│  These values are NOT printed here intentionally.        │${NC}"
echo -e "${BOLD}└──────────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "${YELLOW}⚡ One manual step remaining:${NC}"
echo ""
echo "   Open .env.oss and add your Alpaca Paper-Trading API keys:"
echo ""
echo -e "   ${CYAN}ALPACA_API_KEY=your_key_here${NC}"
echo -e "   ${CYAN}ALPACA_SECRET_KEY=your_secret_here${NC}"
echo ""
echo "   Free Alpaca Paper-Trading account (no real money required):"
echo "   → https://app.alpaca.markets"
echo ""
echo "   Once done, start the system:"
echo -e "   ${CYAN}docker compose -f docker-compose.oss.yml up -d${NC}"
echo ""
