#!/usr/bin/env bash
# setup.sh — AAAgents OSS First-Time Setup
#
# Generates cryptographically secure secrets and creates .env.oss from the
# bundled template. Run this ONCE before your first `docker compose up`.
#
# Compatible with: macOS, Linux, Git Bash (Windows)
# Requires:        Python 3 (already required by the stack)
#
# Usage:
#   bash setup.sh

set -euo pipefail

ENV_FILE=".env.oss"
ENV_EXAMPLE=".env.oss.example"

# ── Terminal colours (graceful degradation if not supported) ──────────────────
if [ -t 1 ] && command -v tput &>/dev/null && tput colors &>/dev/null 2>&1; then
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    CYAN='\033[0;36m'
    RED='\033[0;31m'
    BOLD='\033[1m'
    NC='\033[0m'
else
    GREEN=''; YELLOW=''; CYAN=''; RED=''; BOLD=''; NC=''
fi

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║        AAAgents OSS — First-Time Setup                   ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

# ── Guard: don't overwrite existing config ────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}⚠  .env.oss already exists — skipping.${NC}"
    echo ""
    echo "   Your existing configuration is unchanged."
    echo "   To regenerate from scratch: rm .env.oss && bash setup.sh"
    echo ""
    exit 0
fi

# ── Pre-flight checks ─────────────────────────────────────────────────────────
if [ ! -f "$ENV_EXAMPLE" ]; then
    echo -e "${RED}❌ .env.oss.example not found.${NC}"
    echo "   Make sure you are in the aaagents-oss root directory."
    exit 1
fi

# Resolve a real Python 3.8+ interpreter.
#
# We probe each candidate by actually running it, not just by `command -v`.
# Reason: on default Windows 11 there is a Microsoft-Store alias at
# C:\Users\<u>\AppData\Local\Microsoft\WindowsApps\python3.exe that satisfies
# `command -v python3` but exits non-zero on real invocation, which would
# silently abort this script under `set -euo pipefail` later. The version
# probe runs symmetrically against python3 and python and picks the first
# candidate that is genuinely Python 3.8+.
PYTHON=""
for cand in python3 python; do
    if command -v "$cand" >/dev/null 2>&1 \
        && "$cand" -c "import sys; sys.exit(0 if sys.version_info >= (3, 8) else 1)" >/dev/null 2>&1; then
        PYTHON="$cand"
        break
    fi
done
if [ -z "$PYTHON" ]; then
    echo -e "${RED}❌ Python 3.8+ not found.${NC}"
    echo "   Microsoft Store stubs (python3.exe redirector) do not count."
    echo "   Install Python 3 from https://www.python.org/downloads/ and retry."
    exit 1
fi

# ── Generate secrets ──────────────────────────────────────────────────────────
echo "Generating cryptographically secure secrets..."

POSTGRES_PASSWORD=$("$PYTHON" -c "import secrets; print(secrets.token_hex(24))")
PROXY_SECRET=$("$PYTHON" -c "import secrets; print(secrets.token_hex(32))")
REDIS_PASSWORD=$("$PYTHON" -c "import secrets; print(secrets.token_hex(24))")

# Sanity check — should never fail, but fail loudly if it does
if [ -z "$POSTGRES_PASSWORD" ] || [ -z "$PROXY_SECRET" ] || [ -z "$REDIS_PASSWORD" ]; then
    echo -e "${RED}❌ Secret generation failed — Python output was empty.${NC}"
    exit 1
fi

# ── Write .env.oss ────────────────────────────────────────────────────────────
# Use awk for portable replacement of the empty POSTGRES_PASSWORD= line.
awk -v pw="$POSTGRES_PASSWORD" '
    /^POSTGRES_PASSWORD=[[:space:]]*$/ { print "POSTGRES_PASSWORD=" pw; next }
    { print }
' "$ENV_EXAMPLE" > "$ENV_FILE"

# Append the auto-generated PROXY + REDIS sections.
#
# Use printf with single-quoted format strings instead of a heredoc, so that
# token contents (currently hex; if future versions switch to url-safe base64
# the +/= chars would be safe under shell interpolation) never get re-evaluated
# by the shell. ASCII-only separators keep the file readable on macOS bash 3.2,
# which does not support `printf '\uXXXX'` Unicode escapes (would emit literal
# `\u2500` text instead of `-`).
printf '\n' >> "$ENV_FILE"
printf '# --- Internal Service Authentication -----------------------------------------\n' >> "$ENV_FILE"
printf '# Auto-generated by setup.sh -- do NOT commit this file or share these values.\n' >> "$ENV_FILE"
printf '# HMAC-SHA256 key signing requests from the Public API to the Backend Engine.\n' >> "$ENV_FILE"
printf 'PROXY_ENGINE_SHARED_SECRET=%s\n' "$PROXY_SECRET" >> "$ENV_FILE"
printf '\n' >> "$ENV_FILE"
printf '# --- Redis Auth --------------------------------------------------------------\n' >> "$ENV_FILE"
printf '# Auto-generated by setup.sh -- required by docker-compose.oss.yml\n' >> "$ENV_FILE"
printf '# (redis-server --requirepass) and embedded in REDIS_URL by both the backend\n' >> "$ENV_FILE"
printf '# and the public-api services.\n' >> "$ENV_FILE"
printf 'REDIS_PASSWORD=%s\n' "$REDIS_PASSWORD" >> "$ENV_FILE"

# ── Create required directories ───────────────────────────────────────────────
mkdir -p data plugins

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}✅ .env.oss created successfully.${NC}"
echo ""
echo -e "${BOLD}┌──────────────────────────────────────────────────────────┐${NC}"
echo -e "${BOLD}│  Auto-generated secrets (stored only in .env.oss):       │${NC}"
echo -e "${BOLD}│                                                          │${NC}"
echo -e "${BOLD}│  POSTGRES_PASSWORD            ✓  generated               │${NC}"
echo -e "${BOLD}│  PROXY_ENGINE_SHARED_SECRET   ✓  generated               │${NC}"
echo -e "${BOLD}│  REDIS_PASSWORD               ✓  generated               │${NC}"
echo -e "${BOLD}│                                                          │${NC}"
echo -e "${BOLD}│  These values are NOT printed here intentionally.        │${NC}"
echo -e "${BOLD}└──────────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "${YELLOW}⚡ One manual step remaining:${NC}"
echo ""
echo "   Open .env.oss and add your Alpaca Paper-Trading API keys:"
echo ""
echo -e "   ${CYAN}ALPACA_API_KEY=your_key_here${NC}"
echo -e "   ${CYAN}ALPACA_SECRET_KEY=your_secret_here${NC}"
echo ""
echo "   Free Alpaca Paper-Trading account (no real money required):"
echo "   → https://app.alpaca.markets"
echo ""
echo "   Once done, start the system:"
echo -e "   ${CYAN}docker compose --env-file .env.oss -f docker-compose.oss.yml up -d${NC}"
echo ""
