# setup.ps1 — AAAgents OSS First-Time Setup (Windows PowerShell)
#
# Generates cryptographically secure secrets and creates .env.oss from the
# bundled template. Run this ONCE before your first `docker compose up`.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File setup.ps1
#   (or right-click → "Run with PowerShell")

$ErrorActionPreference = "Stop"

$EnvFile    = ".env.oss"
$EnvExample = ".env.oss.example"

Write-Host ""
Write-Host "╔══════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║        AAAgents OSS — First-Time Setup                   ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# ── Guard: don't overwrite existing config ─────────────────────────────────────
if (Test-Path $EnvFile) {
    Write-Host "⚠  .env.oss already exists — skipping." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "   Your existing configuration is unchanged."
    Write-Host "   To regenerate from scratch: Remove-Item .env.oss; .\setup.ps1"
    Write-Host ""
    exit 0
}

# ── Pre-flight checks ──────────────────────────────────────────────────────────
if (-not (Test-Path $EnvExample)) {
    Write-Host "❌ .env.oss.example not found." -ForegroundColor Red
    Write-Host "   Make sure you are in the aaagents-oss root directory."
    exit 1
}

# Resolve Python
$PythonCmd = $null
foreach ($cmd in @("python3", "python")) {
    try {
        $ver = & $cmd --version 2>&1
        if ($ver -match "Python 3") { $PythonCmd = $cmd; break }
    } catch { }
}
if (-not $PythonCmd) {
    Write-Host "❌ Python 3 not found." -ForegroundColor Red
    Write-Host "   Install Python 3 from https://www.python.org/downloads/ and retry."
    exit 1
}

# ── Generate secrets ───────────────────────────────────────────────────────────
Write-Host "Generating cryptographically secure secrets..."

$PostgresPassword = & $PythonCmd -c "import secrets; print(secrets.token_hex(24))"
$ProxySecret      = & $PythonCmd -c "import secrets; print(secrets.token_hex(32))"

if (-not $PostgresPassword -or -not $ProxySecret) {
    Write-Host "❌ Secret generation failed — Python output was empty." -ForegroundColor Red
    exit 1
}

# ── Write .env.oss ─────────────────────────────────────────────────────────────
# Read template, replace empty POSTGRES_PASSWORD= line, append PROXY secret.
$content = Get-Content $EnvExample -Raw -Encoding UTF8

# Replace the empty POSTGRES_PASSWORD= line (handles trailing whitespace/CRLF)
$content = $content -replace '(?m)^POSTGRES_PASSWORD=[ \t]*(\r?\n)', "POSTGRES_PASSWORD=$PostgresPassword`n"

# Append PROXY_ENGINE_SHARED_SECRET section
$content = $content.TrimEnd()
$content += @"

`n
# --- Internal Service Authentication -----------------------------------------
# Auto-generated by setup.ps1 -- do NOT commit this file or share this value.
# This HMAC secret authenticates requests between the Public API and the
# Backend Engine. Both services must share the identical value.
PROXY_ENGINE_SHARED_SECRET=$ProxySecret
"@

# WriteAllText with UTF8Encoding($false) intentionally writes LF (not CRLF).
# Docker reads .env files expecting LF line endings regardless of host OS.
# This is correct behaviour — do not change to Set-Content which adds CRLF.
[System.IO.File]::WriteAllText((Join-Path (Get-Location) $EnvFile), $content, [System.Text.UTF8Encoding]::new($false))

# ── Create required directories ────────────────────────────────────────────────
New-Item -ItemType Directory -Force -Path "data" | Out-Null
New-Item -ItemType Directory -Force -Path "plugins" | Out-Null

# ── Summary ────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "✅ .env.oss created successfully." -ForegroundColor Green
Write-Host ""
Write-Host "┌──────────────────────────────────────────────────────────┐"
Write-Host "│  Auto-generated secrets (stored only in .env.oss):       │"
Write-Host "│                                                          │"
Write-Host "│  POSTGRES_PASSWORD            ✓  generated               │"
Write-Host "│  PROXY_ENGINE_SHARED_SECRET   ✓  generated               │"
Write-Host "│                                                          │"
Write-Host "│  These values are NOT printed here intentionally.        │"
Write-Host "└──────────────────────────────────────────────────────────┘"
Write-Host ""
Write-Host "⚡ One manual step remaining:" -ForegroundColor Yellow
Write-Host ""
Write-Host "   Open .env.oss and add your Alpaca Paper-Trading API keys:"
Write-Host ""
Write-Host "     ALPACA_API_KEY=your_key_here"    -ForegroundColor Cyan
Write-Host "     ALPACA_SECRET_KEY=your_secret_here" -ForegroundColor Cyan
Write-Host ""
Write-Host "   Free Alpaca Paper-Trading account (no real money required):"
Write-Host "   → https://app.alpaca.markets"
Write-Host ""
Write-Host "   Once done, start the system:"
Write-Host "   → docker compose -f docker-compose.oss.yml up -d" -ForegroundColor Cyan
Write-Host ""
