import { useEffect, useRef, useState } from "react";
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer } from "recharts";
import { runSimulation, getSimulationResult, type SimulationResult } from "@/lib/api";
import { IconLightbulb } from "@/console/shared/Icons";

// SIM-1 T1 (#1484): the Console Simulation page. The user picks a date range + initial capital +
// universe, runs a backtest over that period, and sees the strategy equity curve vs. the S&P 500.
// Results come from GET /simulation-result (Dual-Design Option B): we poll it continuously, so the
// page reflects an in-flight run even after a page reload (the engine holds the result in memory).
// A backtest is informational ONLY — the mandatory simulated/not-advice/past-performance/AI framing
// (EU AI Act Art. 50) is shown prominently. Styled to the Console design system (eyebrow / surface /
// KPI cards) to match Overview & the other pages: the result structure is ALWAYS visible (values
// fill in after a run), like Overview's always-present equity surface + KPI cards.
type RunState = "idle" | "running" | "complete" | "error";

const INPUT =
  "w-full rounded-lg bg-black/40 border border-white/12 px-3 py-2 text-[13px] text-white/90 outline-none focus:border-white/30 transition-colors";
const PRIMARY =
  "text-[12.5px] font-semibold px-4 py-2 rounded-lg border border-[#00c27a]/30 bg-[#00c27a]/12 text-[#00c27a] hover:bg-[#00c27a]/20 disabled:opacity-40 disabled:cursor-not-allowed transition-colors";

export function Simulation() {
  const [startDate, setStartDate] = useState("2024-01-01");
  const [endDate, setEndDate] = useState("2024-12-31");
  const [initialCapital, setInitialCapital] = useState("100000");
  const [universe, setUniverse] = useState<"sp500" | "full_market">("sp500");
  const [state, setState] = useState<RunState>("idle");
  const [result, setResult] = useState<SimulationResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const timer = useRef<number | null>(null);

  useEffect(() => {
    let active = true;
    const tick = async () => {
      try {
        const r = await getSimulationResult();
        if (!active) return;
        if (r.status === "running") {
          setState("running");
        } else if (r.status === "complete") {
          setState("complete");
          setResult(r);
        }
      } catch {
        /* engine may be down — keep polling */
      }
      if (active) timer.current = window.setTimeout(tick, 2000);
    };
    tick();
    return () => {
      active = false;
      if (timer.current) window.clearTimeout(timer.current);
    };
  }, []);

  async function handleRun() {
    setError(null);
    setResult(null);
    setState("running");
    try {
      const r = await runSimulation({
        start_date: startDate,
        end_date: endDate,
        initial_capital: parseFloat(initialCapital) || 0,
        symbol_sample_mode: universe,
      });
      if (r.status !== "success") {
        setState("error");
        setError(r.message || "Could not start the simulation.");
      }
    } catch {
      setState("error");
      setError("Engine not reachable.");
    }
  }

  const chartData = mergeEquity(result);
  const running = state === "running";

  return (
    <div className="px-8 py-7 space-y-7 max-w-[1100px]">
      <div>
        <div className="eyebrow mb-2">Backtest & Paper Trading</div>
        <h1 className="text-[40px] font-bold tracking-tight3 leading-[1.05] text-white/92">Simulation</h1>
      </div>

      {/* Consolidated explanation box (designed matching Decisions & Reports pages) */}
      <div className="surface-flat rounded-xl px-5 py-4 flex items-start gap-3">
        <IconLightbulb width={16} height={16} className="text-white/70 mt-1 shrink-0" />
        <div className="text-[13.5px] text-white/70 leading-relaxed space-y-2">
          <p>
            <span className="font-semibold text-white/90">Strategy Simulation.</span>{" "}
            Backtest the autonomous strategy over a historical period and compare its performance against the S&P 500 index.
          </p>
          <p className="text-[13px] text-white/45">
            <span className="text-white/60">Tip:</span> Simulated performance is generated by an autonomous AI system for informational purposes only, does not reflect real trades, and is not investment advice. Past performance is not indicative of future results.
          </p>
        </div>
      </div>

      {/* Backtest configuration */}
      <div className="surface p-6">
        <div className="eyebrow mb-4">Backtest configuration</div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
          <div className="flex flex-col gap-1.5">
            <label htmlFor="sim-start" className="text-[11px] text-white/50">
              Start date
            </label>
            <input
              id="sim-start"
              type="date"
              value={startDate}
              onChange={(e) => setStartDate(e.target.value)}
              className={INPUT}
            />
          </div>
          <div className="flex flex-col gap-1.5">
            <label htmlFor="sim-end" className="text-[11px] text-white/50">
              End date
            </label>
            <input
              id="sim-end"
              type="date"
              value={endDate}
              onChange={(e) => setEndDate(e.target.value)}
              className={INPUT}
            />
          </div>
          <div className="flex flex-col gap-1.5">
            <label htmlFor="sim-capital" className="text-[11px] text-white/50">
              Initial capital (USD)
            </label>
            <input
              id="sim-capital"
              type="number"
              min="0"
              value={initialCapital}
              onChange={(e) => setInitialCapital(e.target.value)}
              className={INPUT}
            />
          </div>
          <div className="flex flex-col gap-1.5">
            <label htmlFor="sim-universe" className="text-[11px] text-white/50">
              Universe
            </label>
            <select
              id="sim-universe"
              value={universe}
              onChange={(e) => setUniverse(e.target.value as "sp500" | "full_market")}
              className={INPUT}
            >
              <option value="sp500">S&amp;P 500</option>
              <option value="full_market">Full market</option>
            </select>
          </div>
        </div>

        <div className="flex items-center gap-3 mt-5">
          <button onClick={handleRun} disabled={running} className={PRIMARY}>
            {running ? (
              <span className="inline-flex items-center gap-2">
                <span
                  aria-hidden
                  className="inline-block w-3.5 h-3.5 rounded-full border-2 border-[#00c27a]/30 border-t-[#00c27a] animate-spin"
                />
                Running backtest…
              </span>
            ) : (
              "Run simulation"
            )}
          </button>
          {error && <span className="text-[12px] text-[#ff8a80]">{error}</span>}
        </div>

        {/* SIM-1 T3 (#1486): honest methodology — the sim news/sentiment is simulated, no paid feed. */}
        <p className="text-[10.5px] text-white/35 mt-5 leading-relaxed max-w-2xl">
          Methodology: news &amp; sentiment in this backtest are{" "}
          <strong className="text-white/55">simulated</strong>, not a live news feed — results reflect
          price and model behaviour. No external paid data source is used. Returns are net of modeled
          slippage + commission.
        </p>
      </div>

      {/* SIM-1 T2 (#1485): honest survivorship signal — shown after a completed run. */}
      {state === "complete" &&
        result &&
        (result.survivorship_adjusted ? (
          <p className="text-[11.5px] text-white/45">
            Universe: <strong className="text-white/70">point-in-time S&amp;P 500</strong> —
            survivorship-adjusted (best-effort, from a limited historical-membership set).
          </p>
        ) : (
          <div
            className="surface p-3.5 text-[11.5px] leading-relaxed"
            style={{ borderColor: "rgba(255,170,0,0.35)" }}
          >
            <strong className="text-[#ffcc66]">⚠ Survivorship bias:</strong>{" "}
            <span className="text-white/55">
              this run used the current index for past dates (no point-in-time membership). Returns
              may be optimistic — stocks later removed from the index are excluded.
            </span>
          </div>
        ))}

      {/* Results — structure ALWAYS visible (values fill in after a run), like Overview. */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <Kpi
          label="Total return"
          value={result ? fmtPct(result.total_return) : "—"}
          hint="vs. start of period"
          color={
            result?.total_return != null
              ? result.total_return >= 0
                ? "text-bull"
                : "text-bear"
              : undefined
          }
        />
        <Kpi label="Final equity" value={result ? fmtUsd(result.final_equity) : "—"} hint="end of period · USD" />
        <Kpi label="Trades" value={result ? String(result.trades_count ?? "—") : "—"} hint="executed" />
        <Kpi
          label="Period"
          value={result ? `${result.start_date ?? ""} → ${result.end_date ?? ""}` : "—"}
          hint="backtest range"
        />
      </div>

      {/* Honest metrics — return alone is misleading; show risk-adjusted + benchmark-relative. */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <Kpi
          label="Sharpe (annual)"
          value={result?.metrics?.sharpe_ratio_annual != null ? result.metrics.sharpe_ratio_annual.toFixed(2) : "—"}
          hint="risk-adjusted return"
        />
        <Kpi
          label="Max drawdown"
          value={result?.metrics?.max_drawdown_pct != null ? fmtPct(result.metrics.max_drawdown_pct) : "—"}
          hint="peak-to-trough"
          color={result?.metrics?.max_drawdown_pct != null ? "text-bear" : undefined}
        />
        <Kpi
          label="vs S&P 500"
          value={result?.outperformance != null ? fmtPct(result.outperformance) : "—"}
          hint="outperformance · alpha"
          color={
            result?.outperformance != null
              ? result.outperformance >= 0
                ? "text-bull"
                : "text-bear"
              : undefined
          }
        />
        <Kpi
          label="S&P 500 return"
          value={result?.spy_return != null ? fmtPct(result.spy_return) : "—"}
          hint="benchmark · same period"
        />
      </div>

      {/* Equity surface — matches the Total-equity surface on Overview; empty-state until a run. */}
      <div className="surface p-6">
        <div className="flex items-center justify-between mb-4 flex-wrap gap-2">
          <div className="eyebrow">Equity curve · strategy vs S&amp;P 500</div>
          <div className="flex items-center gap-4 text-[11px] text-white/55">
            <span className="flex items-center gap-2">
              <span className="w-3 h-[2px] rounded" style={{ background: "#00c27a" }} /> Strategy
            </span>
            <span className="flex items-center gap-2">
              <span
                className="w-3 h-[1px] border-t border-dashed"
                style={{ borderColor: "rgba(212,168,83,0.6)" }}
              />{" "}
              S&amp;P 500
            </span>
          </div>
        </div>
        {chartData.length > 0 ? (
          <div style={{ height: 300 }}>
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={chartData} margin={{ top: 6, right: 10, bottom: 4, left: 0 }}>
                <XAxis
                  dataKey="date"
                  tick={{ fontSize: 9, fill: "#888" }}
                  minTickGap={32}
                  stroke="rgba(255,255,255,0.08)"
                />
                <YAxis
                  tick={{ fontSize: 9, fill: "#888" }}
                  width={52}
                  domain={["auto", "auto"]}
                  stroke="rgba(255,255,255,0.08)"
                />
                <Tooltip
                  contentStyle={{
                    background: "#0d0d0f",
                    border: "1px solid rgba(255,255,255,0.1)",
                    borderRadius: 8,
                    fontSize: 11,
                  }}
                />
                <Line
                  type="monotone"
                  dataKey="strategy"
                  name="Strategy"
                  stroke="#00c27a"
                  dot={false}
                  strokeWidth={1.6}
                />
                <Line
                  type="monotone"
                  dataKey="spy"
                  name="S&P 500"
                  stroke="#d4a853"
                  strokeDasharray="4 3"
                  dot={false}
                  strokeWidth={1.3}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        ) : (
          <div className="h-[300px] flex flex-col items-center justify-center text-center gap-3 text-[12px] px-6">
            {running ? (
              <>
                {/* Spinning wheel so a long backtest reads as "working", not frozen. */}
                <span
                  aria-hidden
                  className="inline-block w-7 h-7 rounded-full border-[3px] border-white/12 border-t-[#00c27a] animate-spin"
                />
                <span className="text-white/55">
                  Running the backtest over your selected period — this can take a while. The equity
                  curve appears here when it completes.
                </span>
              </>
            ) : (
              <span className="text-white/30">
                Run a backtest to see the strategy equity curve vs. the S&amp;P 500.
              </span>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

function Kpi({
  label,
  value,
  hint,
  color,
}: {
  label: string;
  value: string;
  hint: string;
  color?: string;
}) {
  return (
    <div className="surface p-5">
      <div className="eyebrow mb-2.5">{label}</div>
      <div className={`num text-[24px] font-bold leading-none ${color ?? "text-white/92"}`}>
        {value}
      </div>
      <div className="text-[11px] text-white/40 mt-1.5">{hint}</div>
    </div>
  );
}

function mergeEquity(
  result: SimulationResult | null,
): { date: string; strategy?: number; spy?: number }[] {
  if (!result) return [];
  const m: Record<string, { date: string; strategy?: number; spy?: number }> = {};
  (result.strategy_equity ?? []).forEach((p) => {
    m[p.date] = { ...m[p.date], date: p.date, strategy: p.equity };
  });
  (result.spy_equity ?? []).forEach((p) => {
    m[p.date] = { ...m[p.date], date: p.date, spy: p.equity };
  });
  return Object.values(m).sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
}

function fmtPct(v?: number): string {
  return v == null ? "—" : `${v >= 0 ? "+" : ""}${v.toFixed(2)}%`;
}

function fmtUsd(v?: number): string {
  return v == null ? "—" : `$${Math.round(v).toLocaleString()}`;
}
