# core/entitlement/issuer.py
# GTM-1 (#1839) — SERVER-SIDE Ed25519 tier-token ISSUER (the minting counterpart to the
# #1800 verifier in crypto.py). This module MINTS signed license tokens; the desktop only
# ever VERIFIES them (crypto.verify_token). The signing PRIVATE key lives in GCP Secret
# Manager and this code path is CLOUD-ONLY — it must never execute on a customer desktop.
#
# WIRE FORMAT: delegated wholesale to crypto._encode_token so the minter and verifier share
# ONE canonicalisation and can never drift (guarantees round-trip). See crypto.py header.
#
# KEY LIFECYCLE:
#   * The Ed25519 keypair is generated by scripts/entitlement_keygen.py (Brick 4).
#   * The PRIVATE key (32 raw bytes, base64) is stored in Secret Manager as
#     ``entitlement-signing-key`` and loaded here, lazily, only on Cloud Run (K_SERVICE).
#   * The PUBLIC key is baked into crypto.TRUSTED_PUBLIC_KEYS / supplied via
#     AAA_ENTITLEMENT_PUBKEYS so the desktop verifier trusts tokens this issuer mints.
from __future__ import annotations

import base64
import hashlib
import logging
import os
import secrets
from datetime import datetime, timedelta, timezone

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

import config
from core.entitlement import crypto
from core.entitlement.tier import Tier

logger = logging.getLogger(__name__)

# Name of the Secret Manager secret holding the base64 of the 32 raw Ed25519 private bytes.
_SIGNING_KEY_SECRET = "entitlement-signing-key"

# ---------------------------------------------------------------------------
# VORSCHLAG — Product zu bestaetigen (GTM-1 #1839)
# ---------------------------------------------------------------------------
# Default token lifetime. 30 days is a PROPOSAL — Product must confirm the licence
# duration (and any per-tier differences) before this ships.
# ---------------------------------------------------------------------------
ENTITLEMENT_TOKEN_VALID_DAYS = 30


def _require_cloud() -> None:
    """Fail-closed cloud-only guard: token minting must never run on a desktop.

    ``K_SERVICE`` is set by Cloud Run. Refusing to proceed anywhere else keeps the
    signing PRIVATE key from ever being loaded outside the cloud issuer service.
    Precedent: core/database/session.py::_guard_cloud_sqlite_fallback,
    core/llm/provider.py::_guard_cloud_ollama.
    """
    if not os.environ.get("K_SERVICE"):
        raise RuntimeError(
            "[Issuer] token minting is cloud-only (K_SERVICE required); "
            "the private key never runs on the desktop."
        )


def _load_private_key() -> Ed25519PrivateKey:
    """Load the Ed25519 signing key from Secret Manager (lazy; cloud-only).

    Kept lazy so importing this module never touches GCP. Reuses the existing
    SecretManagerServiceClient pattern (core/secret_manager_utils.py) and
    config.GCP_PROJECT_ID. The stored secret is the base64 of the 32 raw private bytes.
    """
    _require_cloud()

    project_id = config.GCP_PROJECT_ID
    if not project_id:
        raise RuntimeError(
            "[Issuer] GCP_PROJECT_ID is not set — cannot load the signing key."
        )

    # Imported lazily: google-cloud-secret-manager is a cloud-only dependency and must
    # not be required to import this module (or run the desktop verifier).
    from google.cloud import secretmanager

    client = secretmanager.SecretManagerServiceClient()
    version_path = (
        f"projects/{project_id}/secrets/{_SIGNING_KEY_SECRET}/versions/latest"
    )
    response = client.access_secret_version(request={"name": version_path})
    raw_b64 = response.payload.data.decode("utf-8").strip()
    private_bytes = base64.b64decode(raw_b64)
    return Ed25519PrivateKey.from_private_bytes(private_bytes)


def mint_tier_token(
    tier: Tier,
    issued_to: str,
    valid_days: int = ENTITLEMENT_TOKEN_VALID_DAYS,
) -> str:
    """Mint a signed, expiring license token for ``tier``.

    Args:
        tier: the Tier to grant.
        issued_to: the raw licensee id. It is SHA256-hashed before it ever hits the
            wire — the raw id is never embedded in the token.
        valid_days: token lifetime in days (default 30 — see ENTITLEMENT_TOKEN_VALID_DAYS,
            a VORSCHLAG Product must confirm).

    Returns:
        The base64 wire-format token (see crypto.py), verifiable by crypto.verify_token.
    """
    expires_at = (datetime.now(timezone.utc) + timedelta(days=valid_days)).isoformat()
    claims = {
        "tier": tier.value,
        "expires_at": expires_at,
        "issued_to": hashlib.sha256(issued_to.encode("utf-8")).hexdigest(),
        "nonce": secrets.token_hex(16),
    }
    private_key = _load_private_key()
    return crypto._encode_token(private_key, claims)  # noqa: SLF001 — package-internal
